import { DatabaseSchema } from 'lubejs';
export const schema: DatabaseSchema = {
  name: 'Test',
  tables: [
    {
      name: 'User',
      schema: 'dbo',
      primaryKey: {
        name: 'PK_User_id',
        isNonclustered: false,
        columns: [{ name: 'id', isAscending: true }],
      },
      columns: [
        {
          type: 'BIGINT',
          name: 'id',
          isNullable: false,
          isIdentity: true,
          identityStartValue: 0,
          identityIncrement: 1,
          isCalculate: false,
          isRowflag: false,
        },
        {
          type: 'VARCHAR(MAX)',
          name: 'name',
          isNullable: false,
          isIdentity: false,
          isCalculate: false,
          isRowflag: false,
          comment: '用户名',
        },
        {
          type: 'VARCHAR(MAX)',
          name: 'password',
          isNullable: false,
          isIdentity: false,
          isCalculate: false,
          isRowflag: false,
          comment: '密码',
        },
        {
          type: 'VARCHAR(MAX)',
          name: 'description',
          isNullable: false,
          isIdentity: false,
          isCalculate: false,
          isRowflag: false,
          comment: '摘要说明',
        },
      ],
      indexes: [],
      foreignKeys: [],
      constraints: [],
      comment: '用户',
    },
    {
      name: 'Order',
      schema: 'dbo',
      primaryKey: {
        name: 'PK_Order_id',
        isNonclustered: false,
        columns: [{ name: 'id', isAscending: true }],
      },
      columns: [
        {
          type: 'BIGINT',
          name: 'id',
          isNullable: false,
          isIdentity: false,
          isCalculate: false,
          isRowflag: false,
          comment: 'ID',
        },
        {
          type: 'DATETIME',
          name: 'date',
          isNullable: false,
          isIdentity: false,
          isCalculate: false,
          isRowflag: false,
          comment: '订单日期',
        },
        {
          type: 'VARCHAR(MAX)',
          name: 'orderNo',
          isNullable: false,
          isIdentity: false,
          isCalculate: false,
          isRowflag: false,
          comment: '订单号',
        },
        {
          type: 'VARCHAR(MAX)',
          name: 'description',
          isNullable: false,
          isIdentity: false,
          isCalculate: false,
          isRowflag: false,
          comment: '摘要说明',
        },
        {
          type: 'NVARCHAR(MAX)',
          name: 'rowflag',
          isNullable: false,
          isIdentity: false,
          isCalculate: false,
          isRowflag: false,
          comment: '行标识',
        },
      ],
      indexes: [],
      foreignKeys: [],
      constraints: [],
      comment: '订单',
    },
    {
      name: 'OrderDetail',
      schema: 'dbo',
      primaryKey: {
        name: 'PK_OrderDetail_id',
        isNonclustered: false,
        columns: [{ name: 'id', isAscending: true }],
      },
      columns: [
        {
          type: 'BIGINT',
          name: 'id',
          isNullable: false,
          isIdentity: false,
          isCalculate: false,
          isRowflag: false,
          comment: 'ID',
        },
        {
          type: 'VARCHAR(MAX)',
          name: 'product',
          isNullable: false,
          isIdentity: false,
          isCalculate: false,
          isRowflag: false,
          comment: '产品名称',
        },
        {
          type: 'INT',
          name: 'count',
          isNullable: false,
          isIdentity: false,
          isCalculate: false,
          isRowflag: false,
          comment: '数量',
        },
        {
          type: 'DECIMAL(18,6)',
          name: 'price',
          isNullable: false,
          isIdentity: false,
          isCalculate: false,
          isRowflag: false,
          comment: '单价',
        },
        {
          type: 'DECIMAL(18,6)',
          name: 'amount',
          isNullable: false,
          isIdentity: false,
          isCalculate: false,
          isRowflag: false,
          comment: '金额',
        },
        {
          type: 'VARCHAR(MAX)',
          name: 'description',
          isNullable: false,
          isIdentity: false,
          isCalculate: false,
          isRowflag: false,
          comment: '摘要说明',
        },
        {
          type: 'BIGINT',
          name: 'orderId',
          isNullable: false,
          isIdentity: false,
          isCalculate: false,
          isRowflag: false,
          comment: '订单Id',
        },
      ],
      indexes: [],
      foreignKeys: [],
      constraints: [],
      comment: '订单明细',
    },
    {
      name: 'Position',
      schema: 'dbo',
      primaryKey: {
        name: 'PK_Position_id',
        isNonclustered: false,
        columns: [{ name: 'id', isAscending: true }],
      },
      columns: [
        {
          type: 'BIGINT',
          name: 'id',
          isNullable: false,
          isIdentity: false,
          isCalculate: false,
          isRowflag: false,
          comment: '职位ID',
        },
        {
          type: 'VARCHAR(MAX)',
          name: 'name',
          isNullable: false,
          isIdentity: false,
          isCalculate: false,
          isRowflag: false,
          comment: '职位名称',
        },
        {
          type: 'VARCHAR(MAX)',
          name: 'description',
          isNullable: false,
          isIdentity: false,
          isCalculate: false,
          isRowflag: false,
          comment: '摘要说明',
        },
      ],
      indexes: [],
      foreignKeys: [],
      constraints: [],
      comment: '职位',
    },
    {
      name: 'Employee',
      schema: 'dbo',
      primaryKey: {
        name: 'PK_Employee_id',
        isNonclustered: false,
        columns: [{ name: 'id', isAscending: true }],
      },
      columns: [
        {
          type: 'BIGINT',
          name: 'id',
          isNullable: false,
          isIdentity: false,
          isCalculate: false,
          isRowflag: false,
          comment: '职员ID',
        },
        {
          type: 'VARCHAR(MAX)',
          name: 'name',
          isNullable: false,
          isIdentity: false,
          isCalculate: false,
          isRowflag: false,
          comment: '姓名',
        },
        {
          type: 'VARCHAR(MAX)',
          name: 'description',
          isNullable: false,
          isIdentity: false,
          isCalculate: false,
          isRowflag: false,
          comment: '摘要说明',
        },
      ],
      indexes: [],
      foreignKeys: [],
      constraints: [],
      comment: '职员',
    },
    {
      name: 'EmployeePosition',
      schema: 'dbo',
      primaryKey: {
        name: 'PK_EmployeePosition_id',
        isNonclustered: false,
        columns: [{ name: 'id', isAscending: true }],
      },
      columns: [
        {
          type: 'BIGINT',
          name: 'id',
          isNullable: false,
          isIdentity: false,
          isCalculate: false,
          isRowflag: false,
          comment: 'ID',
        },
        {
          type: 'INT',
          name: 'positionId',
          isNullable: false,
          isIdentity: false,
          isCalculate: false,
          isRowflag: false,
          comment: '职位ID',
        },
        {
          type: 'INT',
          name: 'employeeId',
          isNullable: false,
          isIdentity: false,
          isCalculate: false,
          isRowflag: false,
          comment: '职员ID',
        },
      ],
      indexes: [],
      foreignKeys: [],
      constraints: [],
    },
    {
      name: 'Organization',
      schema: 'dbo',
      primaryKey: {
        name: 'PK_Organization_id',
        isNonclustered: false,
        columns: [{ name: 'id', isAscending: true }],
      },
      columns: [
        {
          type: 'BIGINT',
          name: 'id',
          isNullable: false,
          isIdentity: false,
          isCalculate: false,
          isRowflag: false,
          comment: '机构ID',
        },
        {
          type: 'VARCHAR(MAX)',
          name: 'name',
          isNullable: false,
          isIdentity: false,
          isCalculate: false,
          isRowflag: false,
          comment: '机构名称',
        },
        {
          type: 'VARCHAR(MAX)',
          name: 'description',
          isNullable: false,
          isIdentity: false,
          isCalculate: false,
          isRowflag: false,
          comment: '摘要说明',
        },
        {
          type: 'BIGINT',
          name: 'parentId',
          isNullable: false,
          isIdentity: false,
          isCalculate: false,
          isRowflag: false,
          comment: '父级机构ID',
        },
      ],
      indexes: [],
      foreignKeys: [],
      constraints: [],
      comment: '机构',
    },
  ],
  views: [],
  procedures: [],
  functions: [],
  sequences: [],
  schemas: [],
  comment: '测试数据库',
};
export default schema;
